name: Every Other Wednesday

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 7 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
            #!/bin/bash
            
            # Get the current year, month, and day
            YEAR=$(date +'%Y')
            MONTH=$(date +'%m')
            DAY=$(date +'%d')
            
            # Count from Sunday (0=Sunday
            FIRST_DAY_WEEKDAY=0
            
            # Calculate the current day's weekday
            CURRENT_WEEKDAY=$(date +'%w')
            
            # Ensure today is Wednesday (3). If not, exit.
            if [ "$CURRENT_WEEKDAY" -ne 3 ]; then
                echo "This script should only be run on a Wednesday."
                exit 1
            fi
            
            # Calculate which Wednesday of the month this is
            WEDNESDAY_OCCURRENCE=$(( (DAY + 6 - (FIRST_DAY_WEEKDAY < 4 ? FIRST_DAY_WEEKDAY + 7 : FIRST_DAY_WEEKDAY) - 1) / 7 + 1 ))
            
            # Print message based on the occurrence
            case $WEDNESDAY_OCCURRENCE in
                1)
                    echo "This is the first Wednesday of the month."
                    ;;
                3)
                    echo "This is the third Wednesday of the month."
                    ;;
                5)
                    echo "This is the fifth Wednesday of the month."
                    ;;
                *)
                    echo "This is not the first, third, or fifth Wednesday of the month."
                    ;;
            esac
            
